### ISSUE TITLE
WP MapShare Error

### ISSUE THREAD

**Issue by huberlabgit** [morehawes/inreach-mapshare#1]
Dear Joe, 

I get the following error in my WP (6.2, Twenty Ten) plugin page: 

[Error] Garmin provided an empty response. Check your MapShare Settings.

In the browser the short code on the webpage provides an empty space. 

The link : share.garmin.com/XXXX otherwise works well in other browsers. The Garmin MapShare sharing and PW are activated as recommended. 

Do you have any idea what could be wrong? 

Daniel

**Comment by morehawes** [comment]
Hi @huberlabgit,

Thanks for reaching out and I am sorry to hear you are experiencing this issue. Do you have a Personal or Professional (group) inReach account?

First off it's worth double checking your date ranges (including the date format YYYY-DD-MM HH-MM) are correct and that data is not being filtered out by date (Garming Explore > Social > Filter MapShare Data).

If you enable Debug mode in the plugin (Settings > inReach Mapshare > Advanced) and generate a Shortcode you should be given a URL like this: https://explore.garmin.com/feed/share/... If you visit this URL your browser should download a KML file which you can open to confirm if data is available or not.

I hope this helps, please do let me know if this is not the case.

Cheers,

Joe

**Comment by morehawes** [comment]
Closing as I believe this has been fixed in [v1.2](https://github.com/morehawes/inreach-mapshare/releases/tag/1.2).

Joe
